export default {
    LUMS_API_URL: process.env.REACT_APP_API_URL,
    EMAIL_SERVICE_ID: process.env.REACT_APP_EMAIL_SERVICE_ID,
    EMAIL_USER_ID: process.env.REACT_APP_EMAIL_USER_ID,
    EMAIL_TEMPLATE_ID: process.env.REACT_APP_EMAIL_TEMPLATE_ID,
    DEMO_PASSWORD: process.env.REACT_APP_DEMO_PASSWORD
};